#!/bin/sh -e
case "$1" in
  start)
    echo "Starting mongodb"
    # Use this method for master/slave
    #/usr/local/mongodb/bin/mongod --master --port 27017 --dbpath /db/mongodb/master/ --logpath /var/log/mongodb.log --logappend --fork --smallfiles
    #/usr/local/mongodb/bin/mongod --slave --source localhost --port 27018 --dbpath /db/mongodb/slave/ --logpath /var/log/mongodb.log --logappend --fork --smallfiles
  
    # Start up single instance
    /usr/local/mongodb/bin/mongod --port 27017 --dbpath /db/mongodb/master/ --logpath /var/log/mongodb.log --logappend --fork --smallfiles
  ;;

  stop)
    echo "Stopping mongodb"
    pkill mongod
  ;;
esac