export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export SHELL="zsh"
export EDITOR="/usr/bin/vi"
export PAGER="/usr/bin/less"
export PS1='%n@%m:%~> '
export PS2='> '

umask 022

bindkey -e

precmd () {print -Pn "\e]0;%n@%m: %~\a"}

### aliases
alias root='su root -c "export HOME=$HOME; exec $SHELL"'
